### ISSUE TITLE
Add user creation date and time to the passwords hash generation

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#115]

**Comment by khlr** [comment]
So this should be a new database column alongside the hash column?

**Comment by DmitrySikorsky** [comment]
I just think that we should generate the password hash including something unique for the user, to avoid situation when you can understand that someone's password is the same as yours one, because your hash is the same. Maybe we should use username, or email instead of the creation datetime. I think email is good option too, and user will have to type his password in order to change the credential's email (to generate new hash). What do you think?

**Comment by khlr** [comment]
Ah, now I see. You're talking about something like `md5hash(secret + email)` to generate unique hashes. I think in the future this won't be necessary, when #131 is completed. When that issue is solved, hashes should include a random salt, which makes each hash unique.

Right now, the situation is like this:
`md5hash("top secret")` returns something like `58b014cd...`
`md5hash("top secret")` returns something like `58b014cd...`

When including a user-specific property, you could achieve uniqueness:
`md5hash("top secret" + "your mail")` returns something like `d01c3415...`
`md5hash("top secret" + "my mail")` returns something like `de27a30c...`

But you'll achieve that uniqueness anyways with #131:
`pbkdf2hashWithSalt("salt a" + "top secret")` returns something like `7e58a720...`
`pbkdf2hashWithSalt("salt b" + "top secret")` returns something like `f7747b52...`

Well, long story short: #115 could be dropped in favor of #131.

**Comment by DmitrySikorsky** [comment]
Ha, that is good news :) But how will we validate the password? Should we generate salt each time? Or it works in some other way? I mean, how to generate  "salt a" when we have to validate the password when the hash is already stored in the db?

**Comment by khlr** [comment]
The password verification process will become a little bit more complex. You'll have to store the generated salt for each record alongside the hash. Let's assume the salt that's generated when user "Alice" registers an account is `ab-cd-...` and that the PBKDF2 hash (`h(salt + password string`) is `ef-01-...`. You'd then store the concatenated string in the database for that user: `ab-cd-...-ef-01-...`.

When at some point in time Alice tries to login, you'll have to retrieve her salt bytes (for example the first 16 bytes of the concatenated string) from the database and use them for the password verification. It'd roughly look like this:

```
var userTryingToLogin = "Alice";
var providedPassword = "top secret";

var salt = GetSaltForUserFromDatabase(userTryingToLogin);
var completeHashedString = GetCompletePasswordStringForUserFromDatabase(userTryingToLogin);
var hashForVerification = PBKDF2Hasher.CreateVerificationHash(providedPassword, salt);
var isCorrect = completeHashedString == hashForVerification;
```

**Comment by DmitrySikorsky** [comment]
So, I'm closing this task. We don't need it anymore because of the #131. Thanks, @khlr!
