### ISSUE TITLE
.Net Core 2.0.0 doesn't build

### ISSUE THREAD

**Issue by nathansizemore** [Platformus/Platformus#126]
Ubuntu 17.04

``` shell
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-zesty-prod zesty main" > /etc/apt/sources.list.d/dotnetdev.list'
```

Download and extract [Platformus-Prod-alpha11](http://platformus.net/files/Platformus-Prod-alpha11.zip).

``` shell
cd webapplication
dotnet WebApplication.dll
```

```
dotnet WebApplication.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.0'.
```

**Comment by DmitrySikorsky** [comment]
It just means that you need to install older .net core SDK.

But.

It is only 2 tasks left to release beta1, which works on .NET Core 2.0. So it will be released in few weeks, after testing. If you want it now, I can send working sample for you now.

**Comment by nathansizemore** [comment]
I'm looking for an open source .net Core CMS to develop against. It would be cool to maybe push it as another branch, maybe a develop branch or something that isn't stable?

**Comment by DmitrySikorsky** [comment]
Everything except that 2 tasks is committed to master branch of the Platformus. So you can take and use. But Platformus is not an application, it is  just a set of packages. So to run it you need host web application. (Take a look at Platformus-Sample project.) And I can't commit new Platformus-Sample, because it uses beta1, which is not present on NuGet still. I have just copied all the sources inside that solution with the host web application and develop in that way.

So  you have next options for now:
1. Use current Platformus-Sample (it is on ASP.NET Core 1.1 and Platformus 1.0.0-alpha21). Then update dependencies and you will have new Platformus 1.0.0-beta1 and .NET Core 2.0.
2. Get my current working Platformus-Sample that uses newest Platformus from Git as sources, not as NuGet packages.
3. Wait a bit (1-2 weeks I think), and beta1 will be released.

You can add my in Skype and I will be happy to help you.

**Comment by DmitrySikorsky** [comment]
Btw, don't use Platformus-Prod-alpha11, it is too old. Use ready to use sample from this page: https://github.com/Platformus/Platformus-Sample

When beta1 is ready, I will create new Platformus-Prod-beta1.
