### ISSUE TITLE
Replace MD5 password hasher

### ISSUE THREAD

**Issue by DmitrySikorsky** [Platformus/Platformus#131]
Now the MD5 hashing algorithm is used here: https://github.com/Platformus/Platformus/blob/master/src/Platformus.Security/MD5Hasher.cs#L15

We need to replace it with a better one:
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing

MD5Hasher class should also be renamed.

**Comment by orzech123123** [comment]
I am going to resolve this issue.

**Comment by DmitrySikorsky** [comment]
Cool! Please let me know if you have any questions.

**Comment by khlr** [comment]
I think the interesting thing about this issue is that it's way more substantial than it may sound in the first place.
One has to realize that simply replacing the `MD5Hasher` class with something like a `PBKDF2Hasher` won't be all that has to be done.

As of yet hashes were only created based on the secret provided by the user. Of course this is better than storing the secrets as cleartext, but if you keep in mind that this is a very weak hashing algorithm and that there was no salt involved yet, the old hashes are merely better than cleartext. Hence it's a good thing that this issue exists and the behavior will be changed!

Since there will be a salt in the future, the database access has to be modified, too. To verify the correctness of a provided secret against an existing stored secret of a user, you'll have to retrieve the salt of the existing stored hash. Then there has to be something like a `bool Verify (string clearText, string storedHash)` method in the hasher class. So what I mean is that it won't be sufficient to give a generated hash to the database layer as it's done now, because a new hash will always be different from a stored hash if you don't take the salt into account.

The next big thing (and that's the really challenging part) is to migrate the hashes of existing users to the new "format". If there are users with MD5 hashes in the database and the hashing algorithm is changed, they won't be able to login anymore.
So I think there are two obvious "strategies":
* Reset everyone's password and force them to create a new one which is then automatically hashed using the new algorithm. From a developer perspective this seems quite easy, but I think this is the most uncomfortable solution for existing users.
* Determine if a "re-hash" is required. What I mean by that is that the application could determine if someone's password is still hashed with the old algorithm. If that's true, the application should re-hash the password using the new algorithm. This is possible since the password is provided in cleartext during each login. I can elaborate a bit more on this if required.

So that's just my two cents that came to my mind while having a glance at this issue :)

**Comment by DmitrySikorsky** [comment]
Hi @khlr! Thank you for the great feedback! I didn't think about the existing users migration. Yes, in this case it would be better to keep the old class too, and try to find the credential firstly using the first algorithm, and then using the old one (if credential hasn't been found using the new algorithm). And if we found the credential using the old algorithm, we can use new one to generate and store the new hash. I think this issue should be fixed together with #115. Because now if users have same passwords they will have the same password hashes, and it is not good.

**Comment by khlr** [comment]
Yes, the way you suggested (try PBKDF2 and if that fails, fall back to MD5) should work. But there's still more to consider:

When switching to PBKDF2, there'll be some more parameters:
* First of all the **salt**. It _could_ for example consist of 16 bytes.
* Then there's the **output length** of the hash. The MSDN example uses 32 bytes.
* The next parameter is the **iteration count**. That's the number of hashing cycles used to slow down the hash calculation. Although the MSDN example uses 10k cycles, I'd suggest using a noticeably higher count. E.g. something like 100k cycles or even more (see [this Stackoverflow answer by Thomas Pornin](https://security.stackexchange.com/a/3993/64723) as a reference and keep in mind that it's from 2011).

So what I'm trying to express is that using an arbitrary iteration count of `x` today will be fine, but e.g. in a year a higher value `y` would be more appropriate. When this happens this would by the third hash implementation (1: MD5, 2: PBKDF2-100k, 3: PBKDF2-yk). 

Then you'll have to tweak the hash verification a bit: You'll have to first check if the generated hash applies to PBKDF2-yk, if not, you'll have to check it against PBKDF2-100k, then against MD5. You see, this becomes quite cumbersome after some time (and after the advent of the n-th implementation).

**Comment by DmitrySikorsky** [comment]
Thank you for sharing this, it's very useful! So yes, I agree, we should go this way. I think I will read about this too. @orzech123123 please take a look at our discussion. Maybe it is not the easiest task to start as I decided :)

**Comment by postb99** [comment]
Wouldn't you directly use .net core PasswordHasher class? It's recommended, at the end of the [MS doc page](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing). It internally manages the salt so there is no need for db change. It does only [1000 iterations](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.Extensions.Identity.Core/PasswordHasher.cs) though. I'm going to use it for my own project.

**Comment by DmitrySikorsky** [comment]
Good idea, @postb99 ! But it seems that it is from the Identity project. I (or anybody else who wants to fix this task) will look at this all and fix. Thank you guys for the help!

**Comment by DmitrySikorsky** [comment]
So, it is done. I didn't create any special migration logic, but added reset password page. So everybody who has old account with old hash will be able to migrate to new hashing method using that page. Also, I will add change password page a bit later.
