### ISSUE TITLE
Doesn't work in bash windows 10

### ISSUE THREAD

**Issue by aisaiev** [Platformus/Platformus#133]
Doesn't work in Windows Subsystem for Linux. Installed the latest version dotnet sdk. On the Windows 10 it works. Please see attached screenshots.
![404](https://user-images.githubusercontent.com/14250165/30895066-66a34e2a-a350-11e7-9fc3-15522b03e016.PNG)
![dotnet](https://user-images.githubusercontent.com/14250165/30895067-66a44d66-a350-11e7-81cf-f82290b040a1.PNG)
![dotnet2](https://user-images.githubusercontent.com/14250165/30895068-66a4d920-a350-11e7-9410-b14778fa0e41.PNG)

**Comment by DmitrySikorsky** [comment]
Hi! If you are using Platformus installer, please, take a look at the log in the command window. I think you will find the line that extensions discovering from path ... skipped because path not found. It is because of the wrong path separator symbol inside the appsettings.json file. Please take a look at it, there are corresponding comments there. Also, installer contains bug that prevents some packages to be copied into the extensions folder too (because of the same thing). I have to not hardcode \ path separator but take the one from the system.

You can run ready to use sample from the GitHub on Linux-based systems for now, while it is not fixed.

**Comment by DmitrySikorsky** [comment]
Please, follow #134
