### ISSUE TITLE
Can you create a few more projects, I don't think there is enough?

### ISSUE THREAD

**Issue by PonchoPowers** [Platformus/Platformus#165]
Can you create a few more projects, purely because I don't think there is enough?

No but seriously, how fine grain are you going to make this? I can't work out where to start!

**Comment by DmitrySikorsky** [comment]
I understand that it can look like overkill, but the project structure is logical. It allows to replace some part of the CMS with custom implementation, while another modules are standard ones.

And if you look at particular extension structure, it is logical too. Entities, data repository abstractions (because we support different storage types), data repository implementations (one for each of the storage types), backend, frontend, API.

Cool thing is that you, for example, may take only one API package, put it into a host web application, and run! So you can run 10 API apps and 1 app for other apps. Now I'm finishing very simplified first version of the ecommerce module, and then docs and tutorials will be improved.

**Comment by PonchoPowers** [comment]
Does it all need to be in the same repo then? Splitting up the repo might make more sense and then nuget can be used to pull in the desired modules.

**Comment by DmitrySikorsky** [comment]
I use the same repo because I work with it as with the solid solution. It is useful while refactoring, while moving something shared in the basic barebone extension etc. In the future, some 3d-party extensions will be done as separate repos, but the main ones I think should be in one place. Maybe this is wrong, will see. I'm fixing the last one, ecommerce extension now. Then I will have more time to think about project structure etc.

**Comment by PonchoPowers** [comment]
I know this is your project but if it were mine the ecommerce modules would be housed in a separate repo. If you come to add search modules, again I'd stick them in a separate repo. I'm using my experience of working with Drupal, which had a massive list of modules, to know that separating them up into logical groups means you only have to pull what you need and don't end up with a lot of unused code.

**Comment by DmitrySikorsky** [comment]
Maybe you are right. I will think about splitting the project into separate repos when version 1.0.0 is released.

**Comment by DmitrySikorsky** [comment]
I will close this issue for now. Please feel free to reopen it any time if you have any additional questions.
