### ISSUE TITLE
Blog (or any multiple objects view) navigation 

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#222]
How to implement (most correctly) the objects view page navigation is quite unclear.
Any real website has to implement navigation like [Prev 1 2 ... 155 Next] if the list of objects is more than N.

Platformus datasources do take into consideration ?skip=x&take=y query string parameters, but UI is quite the question.

The first impulse is to use something like
https://getbootstrap.com/docs/4.5/components/pagination/

plus client-side approach like that
https://stackoverflow.com/questions/8695147/how-to-change-css-attribute-value-based-on-querystring-using-jquery

to hide and show [Prev] and [Next] buttons, but there are several questions/issues here:
1) How to determine the total of objects in view (to populate correct number of navbar buttons)?
2) How to get the localized values for [Prev] and [Next] without a bunch of hardcoded values and messy IFs in the view?
3) Is there a way NOT to reinvent the wheel while implementing pagination over and over again?

So, at the moment I just do not add too much posts to the blog(((, hoping for a clear way to make pagination in Platformus to appear.

**Comment by senadburak** [comment]
rexTexTau,
this is what I do:

SELECT COUNT(1) AS Total FROM SerializedObjects 
	WHERE SerializedObjects.ClassId = 5 
	and SerializedObjects.CultureId = 2

In my case, it works.

Hope this helps.

**Comment by senadburak** [comment]
If you want to see it in action, have a look at

https://mef.unsa.ba/en/novosti

Scroll down to the bottom where the pager appears. There, you can see a total number of entries (ie. 86) and paging in full. Searching/filtering is also working perfect (it is also server side). 

PS. note this is a server side paging (not client side). I implemented it on purpose, because of large amount of images that are part of almost any post. By using server side we initially show only five pages, which is effective. If you select any other page (usually they don't do it often) then we get another five post from the server.

HTH,

Senad

**Comment by DmitrySikorsky** [comment]
Hi @rexTexTau,

You can use something like https://github.com/Platformus/Platformus/blob/master/src/Platformus.Barebone.Backend/Areas/Backend/Views/Shared/_Pager.cshtml

So, all you need to do is to generate URLs with the correct skip/take params.

**Comment by rexTexTau** [comment]
The sample URL should be updated to https://github.com/Platformus/Platformus/blob/master/src/Platformus.Core.Backend/Areas/Backend/Views/Shared/_Pager.cshtml I guess

**Comment by DmitrySikorsky** [comment]
Yes, thank you. There are a lot of changes in the version 3.
