### ISSUE TITLE
[Admin panel] Update corresponding bundle on script/style update

### ISSUE THREAD

**Issue by rexTexTau** [Platformus/Platformus#224]
At the moment, when you make changes to some script or style (both via admin panel or standalone separate editor) you have to manually regenerate the corresponding bundle (Admin panel -> Bundles -> Edit -> Save) to make changes acyally be applied on the site.
One could have have an [Update] button in the bundles list (near [Edit] and [Х]) or a completely automated built-in smart bundle update algo to speed up the process.
Maybe my frontend dev process is somehow somewhere wrong, but there's a lot of time I went through Bundles -> Edit -> Save way to update the bundle to make actual changes applied.

**Comment by DmitrySikorsky** [comment]
This feature (as well as views) will be removed from version 2.0.0. Now we use Platformus on many (almost all) of our projects, and we never use this feature. And when it is used, it only creates problems, because changes are only applied on host, so they are overwritten every publish.

Platformus is CMS for developers, not for end users as I see now. Just to create simple backend for a website or a mobile app. Usually we create backend project with sections we need etc.
